// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file aiserver.proto (package aiserver.v1, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/** Describes the minimal effective-token-limit contract used by the proxy. */
export const file_aiserver: GenFile = /*@__PURE__*/ fileDesc(
  "Cg5haXNlcnZlci5wcm90bxILYWlzZXJ2ZXIudjEiIgoMTW9kZWxEZXRhaWxzEhIKCm1vZGVsX25hbWUYASABKAkiUQodR2V0RWZmZWN0aXZlVG9rZW5MaW1pdFJlcXVlc3QSMAoNbW9kZWxfZGV0YWlscxgBIAEoCzIZLmFpc2VydmVyLnYxLk1vZGVsRGV0YWlscyI1Ch5HZXRFZmZlY3RpdmVUb2tlbkxpbWl0UmVzcG9uc2USEwoLdG9rZW5fbGltaXQYASABKAViBnByb3RvMw==",
);

export type ModelDetails = Message<"aiserver.v1.ModelDetails"> & {
  modelName: string;
};

export const ModelDetailsSchema: GenMessage<ModelDetails> =
  /*@__PURE__*/ messageDesc(file_aiserver, 0);

export type GetEffectiveTokenLimitRequest = Message<"aiserver.v1.GetEffectiveTokenLimitRequest"> & {
  modelDetails?: ModelDetails;
};

export const GetEffectiveTokenLimitRequestSchema: GenMessage<GetEffectiveTokenLimitRequest> =
  /*@__PURE__*/ messageDesc(file_aiserver, 1);

export type GetEffectiveTokenLimitResponse = Message<"aiserver.v1.GetEffectiveTokenLimitResponse"> & {
  tokenLimit: number;
};

export const GetEffectiveTokenLimitResponseSchema: GenMessage<GetEffectiveTokenLimitResponse> =
  /*@__PURE__*/ messageDesc(file_aiserver, 2);
